language: cpp

dist: xenial

compiler:
  - clang
  - gcc
  
os:
 - linux
 - osx
 
arch: 
  - AMD64
  - ppc64le

addons:
  apt:
    packages:
      - zlib1g-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3 -m pip install --user pyOpenSSL==20.0 cryptography==3.2.1 cpp-coveralls; fi

install: true

script:
    - make LIBDEFLATE=no
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test COVERAGE=yes LIBDEFLATE=no; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test COVERAGE=no LIBDEFLATE=no; fi
    - make regression LIBDEFLATE=no
    - PATH=$PATH:$PWD/build/ make -C examples

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --exclude tests --gcov-options '\-lp'; fi
