/*************************************************************************\
 * AdapterRemoval - cleaning next-generation sequencing reads            *
 *                                                                       *
 * Copyright (C) 2011 by Stinus Lindgreen - stinus@binf.ku.dk            *
 * Copyright (C) 2014 by Mikkel Schubert - mikkelsch@gmail.com           *
 *                                                                       *
 * If you use the program, please cite the paper:                        *
 * S. Lindgreen (2012): AdapterRemoval: Easy Cleaning of Next Generation *
 * Sequencing Reads, BMC Research Notes, 5:337                           *
 * http://www.biomedcentral.com/1756-0500/5/337/                         *
 *                                                                       *
 * This program is free software: you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation, either version 3 of the License, or     *
 * (at your option) any later version.                                   *
 *                                                                       *
 * This program is distributed in the hope that it will be useful,       *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 * GNU General Public License for more details.                          *
 *                                                                       *
 * You should have received a copy of the GNU General Public License     *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. *
\*************************************************************************/
#ifndef COMMONTYPES_H
#define COMMONTYPES_H

#include <string>
#include <vector>

typedef std::vector<std::string> string_vec;
typedef string_vec::const_iterator string_vec_citer;


/** Different file-types read / generated by AdapterRemoval. */
enum read_type
{
	/** Mate 1 reads, either read or written by AR. */
    rt_mate_1 = 0,
	/** Mate 2 reads, either read or written by AR. */
    rt_mate_2,
	/** PE reads for which the mate has been discarded. */
    rt_singleton,
	/** Overlapping PE reads merged into a single sequence. */
    rt_collapsed,
	/** Collapsed reads truncated due to trimming of low-quality bases. */
    rt_collapsed_truncated,
    /** Discarded reads; e.g. too short reads. */
    rt_discarded,
    //! End value; not to be used as an argument.
    rt_max
};


#endif
