/*************************************************************************\
 * AdapterRemoval - cleaning next-generation sequencing reads            *
 *                                                                       *
 * Copyright (C) 2022 by Mikkel Schubert - mikkelsch@gmail.com           *
 *                                                                       *
 * This program is free software: you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation, either version 3 of the License, or     *
 * (at your option) any later version.                                   *
 *                                                                       *
 * This program is distributed in the hope that it will be useful,       *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 * GNU General Public License for more details.                          *
 *                                                                       *
 * You should have received a copy of the GNU General Public License     *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. *
\*************************************************************************/
#pragma once

#include <array>  // for array
#include <string> // for string

namespace adapterremoval {

//! Collection of licenses for libraries, etc. used by adapterremoval, including
//! both libraries bundled with the source code and purely external libraries.
const char* const LICENSES =

  // AdapterRemoval itself
  "AdapterRemoval is licensed under the GPL v3 or later:\n"
  "\n"
  "  Copyright (C) 2011 by Stinus Lindgreen - stinus@binf.ku.dk\n"
  "  Copyright (C) 2022 by Mikkel Schubert - mikkelsch@gmail.com\n"
  "\n"
  "  This program is free software; you can redistribute it and/or modify it "
  "under the terms of the GNU General Public License as published by the Free "
  "Software Foundation, either version 3 of the License, or (at your option) "
  "any later version.\n"
  "\n"
  "  This program is distributed in the hope that it will be useful, but "
  "WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY "
  "or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License "
  "for more details.\n"
  "\n"
  "  You should have received a copy of the GNU General Public License\n"
  "  along with this program.  If not, see <http://www.gnu.org/licenses/>.\n"
  "\n"
  "\n"

  // Code based on FastQC (see statistics.*pp)
  "AdapterRemoval incorporates duplication estimation code based on FastQC:\n"
  "  Homepage = https://www.bioinformatics.babraham.ac.uk/projects/fastqc/\n"
  "  License = GPL version 3 or later\n"
  "\n"
  "  Copyright 2010-17 Simon Andrews\n"
  "\n"
  "  FastQC is free software; you can redistribute it and/or modify it under "
  "the terms of the GNU General Public License as published by the Free "
  "Software Foundation; either version 3 of the License, or (at your option) "
  "any later version.\n"
  "\n"
  "  FastQC is distributed in the hope that it will be useful, but WITHOUT ANY "
  "WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS "
  "FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more "
  "details.\n"
  "\n"
  "  You should have received a copy of the GNU General Public License along "
  "with FastQC; if not, write to the Free Software Foundation, Inc., 51 "
  "Franklin St, Fifth Floor, Boston, MA 02110-1301 USA\n"
  "\n"
  "\n"

  // robin_hood
  "AdapterRemoval bundles the robin_hood unordered map/set library:\n"
  "  Homepage = https://github.com/martinus/robin-hood-hashing/\n"
  "  License = MIT license\n"
  "\n"
  "  Copyright (c) 2018-2021 Martin Ankerl\n"
  "\n"
  "  Permission is hereby granted, free of charge, to any person obtaining a "
  "copy of this software and associated documentation files (the "
  "\"Software\"), to deal in the Software without restriction, including "
  "without limitation the rights to use, copy, modify, merge, publish, "
  "distribute, sublicense, and/or sell copies of the Software, and to permit "
  "persons to whom the Software is furnished to do so, subject to the "
  "following conditions:\n"
  "\n"
  "  The above copyright notice and this permission notice shall be included "
  "in all copies or substantial portions of the Software.\n"
  "\n"
  "  THE SOFTWARE IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS "
  "OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE "
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER "
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING "
  "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER "
  "DEALINGS IN THE SOFTWARE.\n"
  "\n"
  "\n"

  // catch2
  "AdapterRemoval bundles the catch2 unit testing library:\n"
  "  Homepage = https://github.com/catchorg/Catch2/\n"
  "  License = Boost Software License - Version 1.0\n"
  "\n"
  "  Copyright (c) 2022 Two Blue Cubes Ltd. All rights reserved.\n"
  "\n"
  "  Permission is hereby granted, free of charge, to any person or "
  "organization obtaining a copy of the software and accompanying "
  "documentation covered by this license (the \"Software\") to use, reproduce, "
  "display, distribute, execute, and transmit the Software, and to prepare "
  "derivative works of the Software, and to permit third-parties to whom the "
  "Software is furnished to do so, all subject to the following:\n"
  "\n"
  "  The copyright notices in the Software and this entire statement, "
  "including the above license grant, this restriction and the following "
  "disclaimer, must be included in all copies of the Software, in whole or in "
  "part, and all derivative works of the Software, unless such copies or "
  "derivative works are solely in the form of machine-executable object code "
  "generated by a source language processor.\n"
  "\n"
  "  THE SOFTWARE IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS "
  "OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
  "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT "
  "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE "
  "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, "
  "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER "
  "DEALINGS IN THE SOFTWARE.\n"
  "\n"
  "\n"

  // isa-l
  "AdapterRemoval uses the Intel(R) Intelligent Storage Acceleration Library:\n"
  "  Homepage = https://github.com/intel/isa-l/\n"
  "  License = BSD-3-Clause license\n"
  "\n"
  "  Copyright(c) 2011-2017 Intel Corporation All rights reserved.\n"
  "\n"
  "  Redistribution and use in source and binary forms, with or without "
  "modification, are permitted provided that the following conditions are "
  "met:\n"
  "\n"
  "    * Redistributions of source code must retain the above copyright "
  "notice, this list of conditions and the following disclaimer.\n"
  "\n"
  "    * Redistributions in binary form must reproduce the above copyright "
  "notice, this list of conditions and the following disclaimer in the "
  "documentation and/or other materials provided with the distribution.\n"
  "\n"
  "    * Neither the name of Intel Corporation nor the names of its "
  "contributors may be used to endorse or promote products derived from this "
  "software without specific prior written permission.\n"
  "\n"
  "  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS "
  "IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, "
  "THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR "
  "PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR "
  "CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, "
  "EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, "
  "PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; "
  "OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, "
  "WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR "
  "OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF "
  "ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
  "\n"
  "\n"

  // Libdeflate
  "AdapterRemoval uses the Libdeflate library:\n"
  "  Homepage = https://github.com/ebiggers/libdeflate\n"
  "  License =  MIT license\n"
  "\n"
  "  Copyright 2016 Eric Biggers\n"
  "\n"
  "  Permission is hereby granted, free of charge, to any person obtaining a "
  "copy of this software and associated documentation files (the "
  "\"Software\"), to deal in the Software without restriction, including "
  "without limitation the rights to use, copy, modify, merge, publish, "
  "distribute, sublicense, and/or sell copies of the Software, and to permit "
  "persons to whom the Software is furnished to do so, subject to the "
  "following conditions:\n"
  "\n"
  "  The above copyright notice and this permission notice shall be included "
  "in all copies or substantial portions of the Software.\n"
  "\n"
  "  THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS "
  "OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE "
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER "
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING "
  "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER "
  "DEALINGS IN THE SOFTWARE.\n"
  "\n"
  "\n"

  // Mimalloc
  "Static builds of adapterremoval use Mimalloc:\n"
  "  Homepage = https://github.com/microsoft/mimalloc\n"
  "  License = MIT license\n"
  "\n"
  "  Copyright (c) 2018-2021 Microsoft Corporation, Daan Leijen\n"
  "\n"
  "  Permission is hereby granted, free of charge, to any person obtaining a "
  "copy of this software and associated documentation files (the "
  "\"Software\"), to deal in the Software without restriction, including "
  "without limitation the rights to use, copy, modify, merge, publish, "
  "distribute, sublicense, and/or sell copies of the Software, and to permit "
  "persons to whom the Software is furnished to do so, subject to the "
  "following conditions:\n"
  "\n"
  "  The above copyright notice and this permission notice shall be included "
  "in all copies or substantial portions of the Software.\n"
  "\n"
  "  THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS "
  "OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, "
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE "
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER "
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING "
  "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER "
  "DEALINGS IN THE SOFTWARE.\n"
  "\n"
  "\n"

  // Pure CSS
  "HTML reports generated by AdapterRemoval make use of Pure CSS:\n"
  "  Homepage = https://github.com/pure-css/\n"
  "  License = Yahoo! Inc. BSD-3-Clause license\n"
  "\n"
  "  Copyright 2013 Yahoo! Inc.\n"
  "\n"
  "  Redistribution and use in source and binary forms, with or without "
  "modification, are permitted provided that the following conditions are "
  "met:\n"
  "\n"
  "    * Redistributions of source code must retain the above copyright "
  "notice, this list of conditions and the following disclaimer.\n"
  "\n"
  "    * Redistributions in binary form must reproduce the above copyright "
  "notice, this list of conditions and the following disclaimer in the "
  "documentation and/or other materials provided with the distribution.\n"
  "\n"
  "    * Neither the name of the Yahoo! Inc. nor the names of its "
  "contributors may be used to endorse or promote products derived from this "
  "software without specific prior written permission.\n"
  "\n"
  "  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS "
  "IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, "
  "THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR "
  "PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL YAHOO! INC. BE LIABLE FOR ANY "
  "DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES "
  "(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR "
  "SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER "
  "CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT "
  "LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY "
  "OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH "
  "DAMAGE.\n"
  "\n"
  "\n"

  // Vega-Lite
  "HTML reports generated by AdapterRemoval make use of Vega-Lite:\n"
  "  Homepage = https://vega.github.io/vega-lite/\n"
  "  License =  BSD-3-Clause license\n"
  "\n"
  "  Copyright (c) 2015, University of Washington Interactive Data Lab. All "
  "rights reserved.\n"
  "\n"
  "  Redistribution and use in source and binary forms, with or without "
  "modification, are permitted provided that the following conditions are "
  "met:\n"
  "\n"
  "    1. Redistributions of source code must retain the above copyright "
  "notice, this list of conditions and the following disclaimer.\n"
  "\n"
  "    2. Redistributions in binary form must reproduce the above copyright "
  "notice, this list of conditions and the following disclaimer in the "
  "documentation and/or other materials provided with the distribution.\n"
  "\n"
  "    3. Neither the name of the copyright holder nor the names of its "
  "contributors may be used to endorse or promote products derived from this "
  "software without specific prior written permission.\n"
  "\n"
  "  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS "
  "IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, "
  "THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR "
  "PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR "
  "CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, "
  "EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, "
  "PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; "
  "OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, "
  "WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR "
  "OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF "
  "ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.";

} // namespace adapterremoval
