name: release

on:
  push:
    tags:
      - "v3.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    outputs:
      release_id: ${{ steps.create_release.outputs.release_id }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Read changelog
        id: changelog
        shell: bash
        run: |
          {
            echo 'TEXT<<EOF'
            sed '1,/^## /d;/^## /,$d' CHANGES.md
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        id: create_release
        with:
          tag: ${{ github.ref }}
          release_name: "AdapterRemoval ${{ github.ref_name }}"
          body: ${{ steps.changelog.outputs.TEXT }}
          file: "examples" # must exist, but won't be uploaded since it's not a file as of v2.11.5
          overwrite: true
          draft: true

  release:
    name: build assets for ${{ matrix.os }} with ${{ matrix.cxx }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux-x86_64
          - os: macos-latest
            arch: macos-aarch64
          - os: windows-latest
            arch: windows-x86_64
      # Do not auto-cancel other runners if one fails
      fail-fast: false

    env:
      CXX: ${{ matrix.cxx }}
      TARGET: "adapterremoval-${{ github.ref_name }}-${{ matrix.arch }}"

    needs: create_draft_release

    steps:
      - name: Disable man-db building
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # This speeds up apt-get, by preventing the man-db step from running
        run: sudo rm -vf /var/lib/man-db/auto-update

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - if: ${{ matrix.os == 'windows-latest' }}
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: ucrt64
          install: |
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-git
            mingw-w64-ucrt-x86_64-isa-l
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-mimalloc
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-python-fastjsonschema
            mingw-w64-ucrt-x86_64-python-sphinx

      - if: ${{ matrix.os != 'windows-latest' }}
        name: dependencies (Unix)
        run: bash scripts/setup-${{ matrix.os }}.sh

      - if: ${{ matrix.os == 'windows-latest' }}
        name: dependencies (Windows)
        shell: msys2 {0}
        run: bash scripts/setup-${{ matrix.os }}.sh

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: setup, build, test, and bundle (Linux)
        run: |
          make static-container static DOCS=true
          bash scripts/build-bundle.sh "build/static/install/" "${TARGET}"

      - if: ${{ matrix.os == 'macos-latest' }}
        name: setup, build, test, and bundle (OSX)
        run: |
          # WORKAROUND: linking mimalloc causes SIGABRT in simd_neon.cpp
          bash scripts/build-common.sh STATIC=true MIMALLOC=false DOCS=true
          bash scripts/build-bundle.sh "build/install/" "${TARGET}"

      - if: ${{ matrix.os == 'windows-latest' }}
        name: setup, build, test, and bundle (Windows)
        shell: msys2 {0}
        run: |
          bash scripts/build-common.sh STATIC=true DOCS=true
          bash scripts/build-bundle.sh "build/install/" "${TARGET}"

      - name: upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        with:
          asset_name: "adapterremoval-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz"
          file: "adapterremoval-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz"
          release_id: ${{ needs.create_draft_release.outputs.release_id }}
          draft: true
