name: SonarQube

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    name: Build and analyze

    runs-on: ubuntu-latest

    steps:
      - name: Audit all outbound calls
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: dependencies
        run: sudo apt-get install -y libisal-dev libdeflate-dev meson ninja-build

      - name: setup
        run: make setup DEBUG=true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands="build/compile_commands.json"
